version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    depends_on: 
      - postgres-db
  postgres-db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_DATABASE
  frontend:
    build:
      context: ./frontend